# Generated by Django 5.0 on 2024-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_image", models.ImageField(upload_to="event_images/")),
                ("event_text", models.CharField(max_length=300)),
            ],
        ),
    ]
