# Generated by Django 5.0 on 2024-01-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=50)),
                ("post_date", models.DateTimeField(auto_now=True)),
                ("post_text", models.CharField(max_length=300)),
                ("post_image", models.ImageField(upload_to="post_images/")),
            ],
        ),
    ]
