# Generated by Django 5.0 on 2024-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="post_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post", name="post_text", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(max_length=200),
        ),
    ]
